### ISSUE TITLE
Wiki/"Associated work items"/"Show more" does not seem to work

### ISSUE THREAD

**Issue by halllo** [TFSExt/Forms#5]
Hi.
Thanks for the great "Linked Wiki pages" extension. It helps us a lot.
We noticed that in the Wiki it shows the work items, that the page was linked to. It shows the first 6 work items and a "Show more" link below. When I click on that link, the drop down closes immediately and no more work items are displayed. The drop down closes regardless of where I click.
Is there anything that can be done to see all associated work items? 
![image](https://user-images.githubusercontent.com/168058/46338598-e22b0480-c630-11e8-9b08-04f1c91d0db3.png)

Kindest regards and thanks again for the great tool.

**Comment by boyko-ant** [comment]
Hi!
Thanks for the feedback, I do appreciate it.
I will try to take a look on it and will update you with more details probably next Monday.

**Comment by boyko-ant** [comment]
Hi @halllo!

I've checked your issue and I was unable to reproduce it. Please check this gif attached, it seems like everything works fine. In case I misunderstood something, please provide detailed steps how to reproduce the bug.

![01](https://user-images.githubusercontent.com/2947605/47180079-500d4680-d328-11e8-815d-fc785c6c0115.gif)

**Comment by boyko-ant** [comment]
Hello again @halllo!

It seems that trying to fight with the bugs at 10PM after a long working day wasn't my best idea.

In any case, I re-read a few more times your message and realized that you were talking about wiki page view, not work item view. And you were talking about links from wiki page to work items, which I marked with red rectangle on a screenshot.

If that is the case, then it has nothing to do with my plugin. My tiny piece of code is about changing work item view only. I didn't do anything with wiki or work item engines.

![01](https://user-images.githubusercontent.com/2947605/47181019-906dc400-d32a-11e8-99ac-9a679e861db5.png)

**Comment by boyko-ant** [comment]
Hi @halllo!

**Comment by halllo** [comment]
Yes.
