### ISSUE TITLE
No linked pages are visible

### ISSUE THREAD

**Issue by PeterVojvoda** [TFSExt/Forms#7]
Hi, I installed the addon but it looks like it does not work. I see only this strange message "please wait for links to be loaded".

**Comment by boyko-ant** [comment]
Hi @PeterVojvoda!
Can you please be more specific? What kind of environment do you have - VSTS (Azure DevOps) or TFS? If it is TFS, then what exact version are you using?

**Comment by PeterVojvoda** [comment]
Hi boyko-ant, I have Azure DevOps (VSTS). I tried the addon with Work Item, User Story and Feature also. Still the same message "please wait for links to be loaded".

**Comment by boyko-ant** [comment]
Hi @PeterVojvoda!

Can I ask you to take a look at javascript dev console for me? I'm not sure what causing that issue, maybe there are somme errors in a console. It will help if you will make a few screenshots and/or copy and paste error messages here.

**Comment by PeterVojvoda** [comment]
Hi @boyko-ant,

so I figured it out. The problem was in IE webbrowser. Scripting was enabled and in same time somehow blocked. We launched VSTS in Chrome and the addon works now. I will investigate it deeply later and I will let you know latest info. You can close this issue.

**Comment by boyko-ant** [comment]
Thanks @PeterVojvoda.

Can I also ask you to adjust your review here https://marketplace.visualstudio.com/items?itemName=boykoant.linked-wiki-pages#review-details
